name: 'action-composite-docker-build-push'
description: 'build and push docker image with dockerfile'
inputs:
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prep
      run: |
        IMAGE_NAME=${{ DEPLOYMENT_NAME }}
        VERSION=latest
        SHORTREF=${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/heads/ops ]]; then
          IMAGE_NAME=${{ DEPLOYMENT_NAME }}-ops
          DOCKERFILE=Dockerfile-ops
        fi
        TAGS="${IMAGE_NAME}:${VERSION},${DOCKER_IMAGE}:${SHORTREF}"
        echo ::set-output name=image_name::${IMAGE_NAME}
        echo ::set-output dockerfile=dockerfile::${DOCKERFILE
      shell: bash
    - name: copy dockerfile
      run: |
        mkdir -p build/docker/service && cp ${{ github.action_path }}/${{ steps.prep.outputs.dockerfile }} build/docker/service && cp ${GITHUB_REPOSITORY#*/}/build/libs/* build/docker/service
      shell: bash
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{inputs.registry_username}}
        password: ${{inputs.registry_password}}
    - name: Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: build/docker/service
        file: ${{ github.action_path }}/${{ steps.prep.outputs.dockerfile }}
        push: true
        tags: ${{ steps.prep.outputs.tags }}