name: 'action-composite-docker-build-push'
description: 'build with proper dockerfile and push docker image to private repo'
inputs:
  ENV:
    description: “Docker private registry url”
    required: false
  # container_registry_login:
  #   description: “Login for image registry”
  #   required: true
  # container_registry_password:
  #   description: “Password for image registry (token for scw)”
  #   required: true
outputs:
  image_not_found:
    description: "Docker image present or no on docker registry"
    value: ${{ steps.check_image.outputs.image_not_found }}
runs:
  using: "composite"
  steps:
    - name: Check if image exist on SCW docker registry
      id: check_image
      run: |
        if ! docker manifest inspect mysql:8.0.29 > /dev/null; then
          echo ::set-output name=image_not_found::image_not_found
        fi
      shell: bash

